name: CI

on:
  push:
    branches:
      - master
      - workflows
    tags:
      - '*'
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        dotnet: [ 3.1.x ]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci:skip')"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore Tool
      run: dotnet tool restore

    - name: Restore Fake
      run: dotnet fake build -t none

    - name: Format.Check
      run: dotnet fake build -t format.check

    - name: Build(Debug)
      run: dotnet fake build -- DEBUG

    - name: Build(Release)
      run: dotnet fake build -- RELEASE

    - name: Test(Debug)
      run: dotnet fake build -t test -- DEBUG

    - name: Test(Release)
      run: dotnet fake build -t test -- RELEASE
